### ISSUE TITLE
Confirmation page

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#101]
This confirmation page is shown to the user after completing the ranking of the projects within a category. The page shows:
- A nice yaaay-message, "you have finished ranking of **Wallet & Wallet tools**" or something along those lines
- The final OP allocation
- A clear call to action to create a list
- A button that takes you to the ranking view if you want to make changes after completing

<img width="987" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/9698363/619de5b0-90b0-4675-9e5c-adb6e7af7982">

## Tasks

- [x] Design
- [x] Implementation

**Comment by mosaeedi** [comment]
<img width="829" alt="Screenshot 2023-11-02 at 3 33 14 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/abaebde0-4cff-45fe-a696-703959728f6c">
What if we use a modal instead of an entire page, this way we don't need to send user to another page. When they tap on Finish ranking, we can show this modal!
@kristoferlund @Zeptimus WDYT?

**Comment by Zeptimus** [comment]
looks simplier i like it, lets discuss it in the call

**Comment by mosaeedi** [comment]
We should have a shorter copy! 
That's too much @Zeptimus. Can you reduce it somehow?

**Comment by mosaeedi** [comment]
<img width="646" alt="Screenshot 2023-11-02 at 5 10 09 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/895a21b2-7f5d-4526-a43d-cabf237e714b">

@kristoferlund

**Comment by kristoferlund** [comment]
@mosaeedi That looks great!
