### ISSUE TITLE
Implement hover states for all buttons and links

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#111]
All buttons / interactive elements should react on mouseover

Including planets

**Comment by mosaeedi** [comment]
I'll work on it first thing tomorrow.

**Comment by kristoferlund** [comment]
@mosaeedi Let us know your progress.

**Comment by mosaeedi** [comment]
It's done.

Please take a look here.

[**Figma link**](https://www.figma.com/file/etPHT7NcL9FfecKZeqZkTI/Pairwise-UI-Design?type=design&node-id=2726-21087&mode=design&t=B7kiA8yJVjgYORxo-4)


<img width="684" alt="Screenshot 2023-11-08 at 5 39 21 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/b5089b94-2994-4262-a345-7b014f12c51e">

**Comment by kristoferlund** [comment]
@mosaeedi Looks good, thanks.

**Comment by yussdev** [comment]
@mosaeedi  We need a more clear contract for this design token ( button ) :
We need to know what kinds of button we in total: Primary, Secondary, .....
So that I can make reusable button component which can be used everywhere this way avoiding in consistency 
For example, what about this button which is black in default state not in hover?
<img width="510" alt="image" src="https://github.com/GeneralMagicio/pw-frontend/assets/51474231/cbe2a28b-5936-47ae-bbfd-c75a6b15eb84">

This way when you use a button in design that will have a name like Primary and we can decide which button we should render based on their names

**Comment by mosaeedi** [comment]
<img width="1087" alt="Screenshot 2023-11-09 at 3 45 17 PM" src="https://github.com/GeneralMagicio/pw-frontend/assets/13708322/37c6cc31-82fa-4786-ac36-269313d9eb5e">

[Link to Figma](https://www.figma.com/file/etPHT7NcL9FfecKZeqZkTI/Pairwise-UI-Design?type=design&node-id=2726-21087&mode=design&t=rpxE92GhDqCt0d8v-4)

**Comment by mosaeedi** [comment]
@yussdev 👆
