### ISSUE TITLE
Updated ranking flow

### ISSUE THREAD

**Issue by kristoferlund** [GeneralMagicio/pw-frontend#152]
When users have finished ranking a few projects, the "Finish" button lights up and the user wants to click it. Currently that means that the category is marked as finished and any additional rankings will not affect the allocation.

After feedback from Griff we should consider the following flow instead:

* Clicking "Finish" does not mean category is marked as finished
* User can go back and make additional ranking to affect allocation
* But, if user makes manual edits on the /ranking page, no more rankings can be done

Warning on ranking page: 

`After making manual adjustments you can't go back and do more pairwise rankings for this category`.

This also means that if users navigates (using back button) to the pairwise ranking page of a category that now doesn't allow ranking, a message is displayed:

`You have made manual adjustments to the ranking of this category and can't do more pairwise rankings. [Link to ranking page]`

**Comment by krisjpi** [comment]
I ran into this in QA and noted it as an issue, or one that I wasn't expecting initially. I think the suggested flow in this issue would fix the cases I ran into and noted.

notes that I made in one of my tests, in case useful:
- Ranking in individuals moons, my ranking doesn't seem to register past the top 8 for any allocation, though I have gone back and voted for them in ranking
- Jumping into initial ranking changes, I can't seem to make a change and get a valid value, I get the "invalid value!" error instead of the "save" button. 
- As soon as I hit the "Finish" button in a moon ranking, it seems to finalize the allocations, and going back to rank more projects does not change the allocations.

If we don't implement the change above, we should probably develop copy to explain that hitting Finish sets the allocations. Copy not needed if the new flow is implemented.

**Comment by kristoferlund** [comment]
🟢 means unlocked
🔴 means locked

### Starting distribution

```
top_category_1 🟢 25% 
top_category_2 🟢 25% 
top_category_3 🟢 25% 
top_category_4 🟢 25% 
```

### Increase `top_category_1` to 70%

- Other categories each hold 1/3 of the remaining 75%.
- New values should represent 1/3 of the new remaining 30%.

```
top_category_1 🟢 70% 
top_category_2 🟢 10% 
top_category_3 🟢 10% 
top_category_4 🟢 10% 
```

### Decrease `top_category_1` to 40%

- Other categories each hold 1/3 of the remaining 30%.
- New values should represent 1/3 of the new remaining 60%.

```
top_category_1 🟢 40% 
top_category_2 🟢 20% 
top_category_3 🟢 20% 
top_category_4 🟢 20% 
```

### Increase `top_category_1` to 70%, one other category locked

- Before change, remaining unlocked categories each held 1/2 of the remaining 20+20=40%
- After change, remaining unlocked categories each hold 1/2 of the remaining 10% = 5%

Before change:
```
top_category_1 🟢 40% 
top_category_2 🟢 20% 
top_category_3 🔴 20% 
top_category_4 🟢 20% 
```


After change:
```
top_category_1 🟢 70% 
top_category_2 🟢 5% 
top_category_3 🔴 20% 
top_category_4 🟢 5% 
```

### Increase `top_category_1` to 90%, one other category locked

- Since `top_category_3` is locked to 20%, changing `top_category_1` means sum is more than 100%.
- **Invalid value**

Before change:
```
top_category_1 🟢 70% (change to 90% not possible)
top_category_2 🟢 5% 
top_category_3 🔴 20% 
top_category_4 🟢 5% 
```

**Comment by kristoferlund** [comment]
After back and forth with @mmahdigh, we landed in these new rules:
- Always: A category not marked as "Finished" cannot be manually edited on the ranking page
- "Finish" button on poll screen becomes "Continue"
- No radical changes to "Continue" modal. 
  - "Create list" also marks category as "Finished"
- Ranking screen:
  - For category that is ranked (WIP) but not finished, add context menu item "Finish ranking". (That category will now have three context menu options: "Continue ranking", "Finish ranking", "Create list")
  - Click on "Finish ranking" shows warning dialog: "No more pairwise ranking possible etc"
- We could consider adding more detail to row labels but I think we are tight on space:
  - "Ranking threshold met" (Our current "Ranked" label)
  - "Ranking finished" (When category is finished, replaces above label)
- List creation modal: 
  - Warn user that no more pairwise ranking will be possible after list creation (since category then is finished)
 
From another perspective, the users: If you want to be able to do manual edits of a category, first you need to meet the pairwise ranking threshold (by doing some rankings), then you need to "finish ranking", either by creating a list or by marking a category as finished on the ranking page.

**Comment by GriffGreen** [comment]
This all sounds GREAT!

The use of "Finish Ranking" is the only thing that sounds weird to me.... think we need to say "Edit Manually"

So I would say:

- Always: A category not marked as "Finished" cannot be manually edited on the ranking page
- "Finish" button on poll screen becomes "Continue"
- No radical changes to "Continue" modal. 
  - "Create list" also marks category as "Finished"
- Ranking screen:
  - For category that is ranked (WIP) but not finished, add context menu item "Finish ranking". (That category will now have three context menu options: "Continue ranking", "Edit manually", "Create list")
  - Click on "Edit manually" shows warning dialog: "No more pairwise ranking will be possible after this"
- We could consider adding more detail to row labels but I think we are tight on space:
  - "Ranking threshold met" (Our current "Ranked" label)
  - "Ranking finished" (When category is finished, replaces above label)
- List creation modal: 
  - Warn user that no more pairwise ranking will be possible after list creation (since category then is finished)
 
From another perspective, the users: **_If you want to be able to do manual edits of a category, first you need to meet the pairwise ranking threshold (by doing some rankings), then you need to agree to "Edit manually", either by creating a list or by marking a category as finished on the ranking page._**
